# Generated by Django 4.0.3 on 2023-08-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_information',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='profileimages'),
        ),
        migrations.AlterField(
            model_name='company_information',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
