# Generated by Django 4.0.3 on 2023-08-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_company_information_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_information',
            name='company_logo',
        ),
    ]
